### ISSUE TITLE
HtmlReport error in rule: EmptyFunctionBlock

### ISSUE THREAD

**Issue by neptu39701** [detekt/detekt#2972]
I found an error in the html report:
- Rule: EmptyFunctionBlock
- Detekt version: 1.11.0
- Stacktrace:
```
java.lang.StringIndexOutOfBoundsException: begin 0, end 59, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3756)
	at java.base/java.lang.String.substring(String.java:1902)
	at io.github.detekt.report.html.HtmlUtilsKt.writeErrorLine(HtmlUtils.kt:51)
	at io.github.detekt.report.html.HtmlUtilsKt.access$writeErrorLine(HtmlUtils.kt:1)
	at io.github.detekt.report.html.HtmlUtilsKt.snippetCode(HtmlUtils.kt:35)
```
- How to reproduce it: <WRITE HERE HOW TO REPRODUCE THIS ISSUE. A CODE SNIPPET IS THE BEST WAY.>

**Comment by BraisGabin** [comment]
Could you share the file that create this error? Or a sample code that reproduce the same issue?

**Comment by neptu39701** [comment]
Sorry I can't reproduce it right now
