### ISSUE TITLE
Detekt fails with error

### ISSUE THREAD

**Issue by krupt** [detekt/detekt#2983]
Getting java.lang.NoClassDefFoundError: Could not initialize class com.pinterest.ktlint.core.ast.ElementType
        at com.pinterest.ktlint.ruleset.standard.ChainWrappingRule.<init>(ChainWrappingRule.kt:36)
        at io.gitlab.arturbosch.detekt.formatting.wrappers.ChainWrapping.<init>(ChainWrapping.kt:15)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.<init>(KtLintMultiRule.kt:56)
        at io.gitlab.arturbosch.detekt.formatting.FormattingProvider.instance(FormattingProvider.kt:26)
        at io.gitlab.arturbosch.detekt.core.Analyzer.<init>(Analyzer.kt:29)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$result$1.invoke(Lifecycle.kt:43)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$result$1.invoke(Lifecycle.kt:23)
        at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.measure(Lifecycle.kt:32)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze(Lifecycle.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.DefaultLifecycle.analyze(Lifecycle.kt:59)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:44)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:21)
        at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:24)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:43)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:25)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.call(Runner.kt:33)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at io.gitlab.arturbosch.detekt.invoke.DefaultCliInvoker.invokeCli(DetektInvoker.kt:53)
        ... 94 more

on running detekt task.
What do I do wrong?

**Comment by arturbosch** [comment]
Hi,
Seems like your using Kotlin 1.4 already.
https://github.com/detekt/detekt/pull/2981 will add support for it.
Note that there are still some remaining issues within ktlint though - https://github.com/pinterest/ktlint/issues/830.
