### ISSUE TITLE
NPE in running gradle baseline task

### ISSUE THREAD

**Issue by ZacSweers** [detekt/detekt#3346]
## Expected Behavior
It should not crash

## Observed Behavior
It crashes with this trace

```
Caused by: java.lang.NullPointerException
        at java.lang.System.arraycopy(Native Method)
        at java.lang.String.getChars(String.java:826)
        at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:316)
        at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:447)
        at io.gitlab.arturbosch.detekt.core.baseline.DelegatingXMLStreamWriter.writeCharacters(DelegatingXMLStreamWriter.kt)
        at io.gitlab.arturbosch.detekt.core.baseline.IndentingXMLStreamWriter.writeEndDocument(IndentingXMLStreamWriter.kt:69)
        at io.gitlab.arturbosch.detekt.core.baseline.BaselineFormat.save(BaselineFormat.kt:85)
        at io.gitlab.arturbosch.detekt.core.baseline.BaselineFormat.write(BaselineFormat.kt:34)
        at io.gitlab.arturbosch.detekt.core.baseline.BaselineFacade.createOrUpdate(BaselineFacade.kt:23)
        at io.gitlab.arturbosch.detekt.core.baseline.BaselineResultMapping.transformFindings(BaselineResultMapping.kt:35)
        at io.gitlab.arturbosch.detekt.core.extensions.ReportingKt.handleReportingExtensions(Reporting.kt:14)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$3.invoke(Lifecycle.kt:50)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$3.invoke(Lifecycle.kt:22)
        at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.measure(Lifecycle.kt:30)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze(Lifecycle.kt:49)
        at io.gitlab.arturbosch.detekt.core.tooling.DefaultLifecycle.analyze(Lifecycle.kt:57)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:43)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:21)
        at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:24)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:25)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.call(Runner.kt:33)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:23)
```

## Steps to Reproduce
I can't reproduce it in a public project unfortunately, but I believe the issue is the stream is being closed and nulling out an internal buffer

## Context
Happens on our project when trying to run `detektBaseline`.

## Your Environment

* Version of detekt used: reproduces on both 1.14.0 and 1.15.0
* Version of Gradle used (if applicable): 6.7.1
* Operating System and version: macOS Big Sur
* Link to your project (if it's a public repository): N/A

**Comment by ZacSweers** [comment]
I'm going to hop in the debugger on my side to try to figure this out but filing for awareness. I've found some other similar issues that support my hunch about

**Comment by ZacSweers** [comment]
Confirmed a closed file is being written to. The problem is here: https://github.com/detekt/detekt/blob/master/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/baseline/IndentingXMLStreamWriter.kt#L67-L70

```kotlin
    override fun writeEndDocument() {
        super.writeEndDocument()
        super.writeCharacters("\n")
    }
```

The `super.writeEndDocument()` closes the underlying document before the `super.writeCharacters("\n")` tries to write another newline

**Comment by ZacSweers** [comment]
Actually I see this is a dupe of #2655. Will fold into there.
