### ISSUE TITLE
Error alerted by IDEA, stack trace

### ISSUE THREAD

**Issue by comdiv** [detekt/detekt#3368]
Was got from IDEA Alerts:

```
java.lang.IllegalStateException: KtElement not inside KtFile: PsiFile:TypeEnhancementKt.class //
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package org.jetbrains.kotlin.load.java.typeEnhancement;

import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.kotlin.builtins.jvm.JavaToKotlinClassMapper;
import org.jetbrains.kotlin.descriptors.ClassDescriptor;
import org.jetbrains.kotlin.descriptors.ClassifierDescriptor;
import org.jetbrains.kotlin.descriptors.annotations.Annotations;
import org.jetbrains.kotlin.descriptors.annotations.CompositeAnnotations;
import org.jetbrains.kotlin.load.java.JvmAnnotationNames;
import org.jetbrains.kotlin.name.FqName;
import org.jetbrains.kotlin.types.KotlinType;
import org.jetbrains.kotlin.types.TypeSystemCommonBackendContext;
import org.jetbrains.kotlin.types.checker.SimpleClassicTypeSystemContext;
import org.jetbrains.kotlin.types.model.KotlinTypeMarker;

@Metadata(
    mv = {1, 4, 0},
    bv = {1, 0, 3},
    k = 2,
    d1 = {"\u0000D\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\u0010 \n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0005\n\u0002\u0010\u000b\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\u001a\u0012\u0010\u0003\u001a\u00020\u0004*\b\u0012\u0004\u0012\u00020\u00040\u0005H\u0002\u001a\"\u0010\u0006\u001a\b\u0012\u0004\u0012\u00020\b0\u0007*\u00020\b2\u0006\u0010\t\u001a\u00020\n2\u0006\u0010\u000b\u001a\u00020\fH\u0002\u001a\u001d\u0010\r\u001a\b\u0012\u0004\u0012\u0002H\u000e0\u0007\"\u0004\b\u0000\u0010\u000e*\u0002H\u000eH\u0002¢\u0006\u0002\u0010\u000f\u001a\u001d\u0010\u0010\u001a\b\u0012\u0004\u0012\u0002H\u000e0\u0007\"\u0004\b\u0000\u0010\u000e*\u0002H\u000eH\u0002¢\u0006\u0002\u0010\u000f\u001a\"\u0010\u0011\u001a\b\u0012\u0004\u0012\u00020\u00120\u0007*\u00020\u00132\u0006\u0010\t\u001a\u00020\n2\u0006\u0010\u000b\u001a\u00020\fH\u0002\u001a\n\u0010\u0014\u001a\u00020\u0012*\u00020\u0013\u001a\u0012\u0010\u0014\u001a\u00020\u0012*\u00020\u00152\u0006\u0010\u0016\u001a\u00020\u0017\u001a\u001d\u0010\u0018\u001a\b\u0012\u0004\u0012\u0002H\u000e0\u0007\"\u0004\b\u0000\u0010\u000e*\u0002H\u000eH\u0002¢\u0006\u0002\u0010\u000f\u001a\n\u0010\u0019\u001a\u00020\u0012*\u00020\f\"\u000e\u0010\u0000\u001a\u00020\u0001X\u0082\u0004¢\u0006\u0002\n\u0000\"\u000e\u0010\u0002\u001a\u00020\u0001X\u0082\u0004¢\u0006\u0002\n\u0000¨\u0006\u001a"},
    d2 = {"ENHANCED_MUTABILITY_ANNOTATIONS", "Lorg/jetbrains/kotlin/load/java/typeEnhancement/EnhancedTypeAnnotations;", "ENHANCED_NULLABILITY_ANNOTATIONS", "compositeAnnotationsOrSingle", "Lorg/jetbrains/kotlin/descriptors/annotations/Annotations;", "", "enhanceMutability", "Lorg/jetbrains/kotlin/load/java/typeEnhancement/EnhancementResult;", "Lorg/jetbrains/kotlin/descriptors/ClassifierDescriptor;", "qualifiers", "Lorg/jetbrains/kotlin/load/java/typeEnhancement/JavaTypeQualifiers;", "position", "Lorg/jetbrains/kotlin/load/java/typeEnhancement/TypeComponentPosition;", "enhancedMutability", "T", "(Ljava/lang/Object;)Lorg/jetbrains/kotlin/load/java/typeEnhancement/EnhancementResult;", "enhancedNullability", "getEnhancedNullability", "", "Lorg/jetbrains/kotlin/types/KotlinType;", "hasEnhancedNullability", "Lorg/jetbrains/kotlin/types/TypeSystemCommonBackendContext;", "type", "Lorg/jetbrains/kotlin/types/model/KotlinTypeMarker;", "noChange", "shouldEnhance", "descriptors.jvm"}
)
public final class TypeEnhancementKt {
    private static final EnhancedTypeAnnotations ENHANCED_NULLABILITY_ANNOTATIONS;
    private static final EnhancedTypeAnnotations ENHANCED_MUTABILITY_ANNOTATIONS;

    public static final boolean hasEnhancedNullability(@NotNull KotlinType $this$hasEnhancedNullability) {
        Intrinsics.checkNotNullParameter($this$hasEnhancedNullability, "$this$hasEnhancedNullability");
        return hasEnhancedNullability((TypeSystemCommonBackendContext)SimpleClassicTypeSystemContext.INSTANCE, (KotlinTypeMarker)$this$hasEnhancedNullability);
    }

    public static final boolean hasEnhancedNullability(@NotNull TypeSystemCommonBackendContext $this$hasEnhancedNullability, @NotNull KotlinTypeMarker type) {
        Intrinsics.checkNotNullParameter($this$hasEnhancedNullability, "$this$hasEnhancedNullability");
        Intrinsics.checkNotNullParameter(type, "type");
        FqName var10002 = JvmAnnotationNames.ENHANCED_NULLABILITY_ANNOTATION;
        Intrinsics.checkNotNullExpressionValue(var10002, "JvmAnnotationNames.ENHANCED_NULLABILITY_ANNOTATION");
        return $this$hasEnhancedNullability.hasAnnotation(type, var10002);
    }

    private static final Annotations compositeAnnotationsOrSingle(List<? extends Annotations> $this$compositeAnnotationsOrSingle) {
        Annotations var10000;
        switch($this$compositeAnnotationsOrSingle.size()) {
        case 0:
            String var1 = "At least one Annotations object expected";
            boolean var2 = false;
            throw (Throwable)(new IllegalStateException(var1.toString()));
        case 1:
            var10000 = (Annotations)CollectionsKt.single($this$compositeAnnotationsOrSingle);
            break;
        default:
            var10000 = (Annotations)(new CompositeAnnotations(CollectionsKt.toList((Iterable)$this$compositeAnnotationsOrSingle)));
        }

        return var10000;
    }

    public static final boolean shouldEnhance(@NotNull TypeComponentPosition $this$shouldEnhance) {
        Intrinsics.checkNotNullParameter($this$shouldEnhance, "$this$shouldEnhance");
        return $this$shouldEnhance != TypeComponentPosition.INFLEXIBLE;
    }

    private static final <T> EnhancementResult<T> noChange(T $this$noChange) {
        return new EnhancementResult($this$noChange, (Annotations)null);
    }

    private static final <T> EnhancementResult<T> enhancedNullability(T $this$enhancedNullability) {
        return new EnhancementResult($this$enhancedNullability, (Annotations)ENHANCED_NULLABILITY_ANNOTATIONS);
    }

    private static final <T> EnhancementResult<T> enhancedMutability(T $this$enhancedMutability) {
        return new EnhancementResult($this$enhancedMutability, (Annotations)ENHANCED_MUTABILITY_ANNOTATIONS);
    }

    private static final EnhancementResult<ClassifierDescriptor> enhanceMutability(ClassifierDescriptor $this$enhanceMutability, JavaTypeQualifiers qualifiers, TypeComponentPosition position) {
        // $FF: Couldn't be decompiled
    }

    private static final EnhancementResult<Boolean> getEnhancedNullability(KotlinType $this$getEnhancedNullability, JavaTypeQualifiers qualifiers, TypeComponentPosition position) {
        // $FF: Couldn't be decompiled
    }

    static {
        FqName var10002 = JvmAnnotationNames.ENHANCED_NULLABILITY_ANNOTATION;
        Intrinsics.checkNotNullExpressionValue(var10002, "JvmAnnotationNames.ENHANCED_NULLABILITY_ANNOTATION");
        ENHANCED_NULLABILITY_ANNOTATIONS = new EnhancedTypeAnnotations(var10002);
        var10002 = JvmAnnotationNames.ENHANCED_MUTABILITY_ANNOTATION;
        Intrinsics.checkNotNullExpressionValue(var10002, "JvmAnnotationNames.ENHANCED_MUTABILITY_ANNOTATION");
        ENHANCED_MUTABILITY_ANNOTATIONS = new EnhancedTypeAnnotations(var10002);
    }
}
 of type class com.intellij.psi.impl.compiled.ClsFileImpl for element FUN of type class org.jetbrains.kotlin.psi.KtNamedFunction
	at org.jetbrains.kotlin.psi.KtElementImplStub.getContainingKtFile(KtElementImplStub.java:79)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.resolveToDescriptorsWithHack(KotlinIndicesHelper.kt:510)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.access$resolveToDescriptorsWithHack(KotlinIndicesHelper.kt:61)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.findSuitableExtensions(KotlinIndicesHelper.kt:600)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.getCallableTopLevelExtensions(KotlinIndicesHelper.kt:172)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.getCallableTopLevelExtensions$default(KotlinIndicesHelper.kt:154)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.getCallableTopLevelExtensions(KotlinIndicesHelper.kt:147)
	at org.jetbrains.kotlin.idea.completion.ReferenceVariantsCollector.doCollectExtensionVariants(ReferenceVariantsCollector.kt:186)
	at org.jetbrains.kotlin.idea.completion.ReferenceVariantsCollector.collectExtensionVariants(ReferenceVariantsCollector.kt:97)
	at org.jetbrains.kotlin.idea.completion.ReferenceVariantsCollector.collectReferenceVariants(ReferenceVariantsCollector.kt:86)
	at org.jetbrains.kotlin.idea.completion.BasicCompletionSession.addReferenceVariantElements(BasicCompletionSession.kt:842)
	at org.jetbrains.kotlin.idea.completion.BasicCompletionSession.access$addReferenceVariantElements(BasicCompletionSession.kt:64)
	at org.jetbrains.kotlin.idea.completion.BasicCompletionSession$ALL$1$doComplete$contextVariableTypesForReferenceVariants$1.invoke(BasicCompletionSession.kt:243)
	at org.jetbrains.kotlin.idea.completion.BasicCompletionSession$ALL$1$doComplete$contextVariableTypesForReferenceVariants$1.invoke(BasicCompletionSession.kt:172)
	at org.jetbrains.kotlin.idea.completion.CompletionSession.withCollectRequiredContextVariableTypes(CompletionSession.kt:402)
	at org.jetbrains.kotlin.idea.completion.BasicCompletionSession$ALL$1.doComplete(BasicCompletionSession.kt:238)
	at org.jetbrains.kotlin.idea.completion.BasicCompletionSession.doComplete(BasicCompletionSession.kt:141)
	at org.jetbrains.kotlin.idea.completion.CompletionSession._complete(CompletionSession.kt:243)
	at org.jetbrains.kotlin.idea.completion.CompletionSession.complete(CompletionSession.kt:218)
	at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor.doComplete(KotlinCompletionContributor.kt:315)
	at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor.doComplete$default(KotlinCompletionContributor.kt:274)
	at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor.performCompletion(KotlinCompletionContributor.kt:267)
	at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor.access$performCompletion(KotlinCompletionContributor.kt:39)
	at org.jetbrains.kotlin.idea.completion.KotlinCompletionContributor$provider$1.addCompletions(KotlinCompletionContributor.kt:57)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:32)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:77)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:32)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:77)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:60)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:133)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.java:41)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$calculateItems$12(CompletionProgressIndicator.java:862)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:179)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:543)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:178)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:858)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:846)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:353)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:345)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by cortinico** [comment]
How is this Detekt related? Also are you using the Detekt IntelliJ Plugin? If so we should move this issue to https://github.com/detekt/detekt-intellij-plugin

**Comment by schalkms** [comment]
> How is this Detekt related?

I’m also interested in an answer to this question. In the stack trace there’s no occurrence of detekt.

**Comment by comdiv** [comment]
Yes, mistakely push it to Detekt. It's some randomely repeated bug with Plugin
