### ISSUE TITLE
[gradle plugin] Adapt access to properties to Configuration Cache

### ISSUE THREAD

**Issue by stephanenicolas** [detekt/detekt#3442]
Using 
* detekt 1.4.12
* JDK:11.0.9 
* AGP:4.2.0-beta04
* Kotlin:1.4.21
* Gradle:6.8

We observe the following error when using `--configuration-caching` (CC) on our build using detekt.

```
- Plugin 'io.gitlab.arturbosch.detekt': read system property 'https.proxyHost'
  See https://docs.gradle.org/6.8/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'io.gitlab.arturbosch.detekt': read system property 'https.proxyPort'
  See https://docs.gradle.org/6.8/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
```

On our side, this problems have often been solved by following: https://docs.gradle.org/6.8/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
 
Thanks for your work already on adapting your plugin to CC. 
Let me know if you need help to resolve this issue.

**Comment by cortinico** [comment]
> * detekt 1.4.12

Please consider bumping to the latest version of Detekt

> We observe the following error when using --configuration-caching (CC) on our build using detekt.

I've naively checked for `proxyHost` and `proxyPort` in our codebase and I found no occurrences of that. It seems like we never read directly that property (though we read others).

**Comment by 3flex** [comment]
There's also existing test coverage for the configuration cache in https://github.com/detekt/detekt/blob/master/detekt-gradle-plugin/src/intTest/kotlin/io/gitlab/arturbosch/detekt/ConfigurationCacheTest.kt

@stephanenicolas do you have an update? If you're still seeing this behaviour on the latest version of detekt can you please provide a stacktrace?

**Comment by 3flex** [comment]
I'm going to close this for now - please reopen if there's more info to share about your issue so it can be investigated, thanks!

**Comment by bmonjoie** [comment]
I got the same error on our CI but not on my machine, after some investigations, I saw that I could reproduce it locally by doing this

```bash
 export JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=proxy.xxxx.xx -Dhttp.proxyPort=3128"; ./gradlew assembleDebug
```

It generates a report which points to [this line](https://github.com/detekt/detekt/blob/v1.17.1/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/internal/DetektAndroid.kt#L73):
```java 
org.gradle.api.InvalidUserCodeException: Read system property 'http.proxyHost'
	at org.gradle.configurationcache.SystemPropertyAccessListener.systemPropertyQueried(SystemPropertyAccessListener.kt:92)
	at org.gradle.internal.classpath.Instrumented$DecoratingProperties.getProperty(Instrumented.java:313)
	at org.gradle.internal.classpath.Instrumented$DecoratingProperties.getProperty(Instrumented.java:307)
	at com.android.build.gradle.internal.SdkLibDataFactory.createProxy(SdkLibDataFactory.kt:99)
	at com.android.build.gradle.internal.SdkLibDataFactory.getSettingsController(SdkLibDataFactory.kt:55)
	at com.android.build.gradle.internal.SdkLibDataFactory.getSdkLibData(SdkLibDataFactory.kt:42)
	at com.android.build.gradle.internal.SdkComponentsBuildService$sdkHandlerDelegate$1.invoke(SdkComponents.kt:102)
	at com.android.build.gradle.internal.SdkComponentsBuildService$sdkHandlerDelegate$1.invoke(SdkComponents.kt:90)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.android.build.gradle.internal.SdkComponentsBuildService.getSdkHandler(SdkComponents.kt:107)
	at com.android.build.gradle.internal.SdkComponentsBuildService.sdkLoader(SdkComponents.kt:289)
	at com.android.build.gradle.internal.scope.GlobalScope.lambda$getVersionedSdkLoader$7(GlobalScope.java:339)
	at org.gradle.api.internal.provider.TransformBackedProvider.mapValue(TransformBackedProvider.java:73)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:65)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
	at org.gradle.api.internal.provider.FlatMapProvider.backingProvider(FlatMapProvider.java:62)
	at org.gradle.api.internal.provider.FlatMapProvider.getProducer(FlatMapProvider.java:71)
	at org.gradle.api.internal.provider.TransformBackedProvider.beforeRead(TransformBackedProvider.java:81)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:63)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:84)
	at com.android.build.gradle.internal.scope.GlobalScope.lambda$getBootClasspath$6(GlobalScope.java:274)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:84)
	at com.android.build.gradle.BaseExtension.getBootClasspath(BaseExtension.kt:410)
	at com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated.getBootClasspath(Unknown Source)
	at io.gitlab.arturbosch.detekt.internal.DetektAndroid$registerTasks$1.execute(DetektAndroid.kt:73)
	at io.gitlab.arturbosch.detekt.internal.DetektAndroid$registerTasks$1.execute(DetektAndroid.kt:21)
```
I see that you changed the way you retrieving this in 1.19.0 and it seems to fix this issue so the solution for now is to use the latest RC

**Comment by 3flex** [comment]
Thanks for a reproducer and stack trace - this is hopefully enough to investigate.

Which version of Android Gradle plugin are you using? And I assume the `assembleDebug` task is being run on your own project, or was that run on detekt itself?

**Comment by bmonjoie** [comment]
I'm using Android Gradle Plugin 7.0.3 and the task was run on my project

**Comment by dsvoronin** [comment]
That's has nothing to do with detekt itself.
Issue from stacktrace is : https://issuetracker.google.com/issues/189730917

**Comment by 3flex** [comment]
@bmonjoie can you please confirm with latest 7.1.0 AGP beta?

**Comment by dsvoronin** [comment]
> @bmonjoie can you please confirm with latest 7.1.0 AGP beta?

or use workaround for versions before:

add to gradle.properties:

```
android.builder.sdkDownload=false
```

**Comment by bmonjoie** [comment]
Sorry, I got swamped and it slipt my mind.
I believe that the new version of Gradle does indeed fix the bug.
This can be closed.
