### ISSUE TITLE
Unable to load class 'com.android.build.gradle.BaseExtension'

### ISSUE THREAD

**Issue by volsahin** [detekt/detekt#3490]
## Steps to Reproduce

I intended to upgrade detekt version from 1.9.1 to latest 1.16.0-RC1 in android project and build failed.
The project uses classic groovy gradle files. It is nice to mention that i apply detekt as a seperate gradle script.

Here is the current detekt.gradle script

```
buildscript {
    ext.detektVersion = '1.9.1'
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:$detektVersion"
    }
}

apply plugin: io.gitlab.arturbosch.detekt.DetektPlugin

detekt {
    // some options
}
```
And that is how it's applied into app
`apply from: '../scripts/detekt.gradle'`

As i see 1.11.1 is the latest version which can be built without a problem. Starting 12.0.0 to the latest version, build fails.
Gradle plugin versions are the latest one.

## Stacktrace

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com/android/build/gradle/BaseExtension

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
Caused by: java.lang.NoClassDefFoundError: com/android/build/gradle/BaseExtension
	at io.gitlab.arturbosch.detekt.internal.DetektAndroid$registerDetektAndroidTasks$1.execute(DetektAndroid.kt:59)
        at io.gitlab.arturbosch.detekt.internal.DetektAndroid$registerDetektAndroidTasks$1.execute(DetektAndroid.kt:21)
Caused by: java.lang.ClassNotFoundException: com.android.build.gradle.BaseExtension
        ... 139 more

* Get more help at https://help.gradle.org

BUILD FAILED in 435ms
```

Also #3476 #3260 these issues experienced similar exceptions as far as i can see.

## Environment
* Version of detekt used: 1.16.0-RC1
* Version of Gradle used (if applicable): 4.1.2
* Version of Kotlin: 1.4.21

**Comment by chao2zhang** [comment]
In your root project, did you apply both detekt plugin and `kotlin-android` plugin? I imagine this is an issue where we accidentally apply detekt to the root project.

**Comment by cortinico** [comment]
> Caused by: java.lang.ClassNotFoundException: com.android.build.gradle.BaseExtension

Which version of AGP are you on?

**Comment by volsahin** [comment]
@chao2zhang actually i didn't applied it inside root project gradle. The `apply from: '../../scripts/detekt.gradle'` snippet is inside of a feature module of a modular application. And @cortinico as i mentioned in environment section, the plugin version is 4.1.2

**Comment by chao2zhang** [comment]
Does your feature module applied `kotlin-android` but not `com.android.application` or other `com.android.*`?

**Comment by volsahin** [comment]
@chao2zhang actually they are not android feature modules, they are basically gradle library modules which i develop features inside them. Because of this, the module gradle file which i applied detekt script contains
```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
```
However when i add detekt dependency also to the app gradle, which contains
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
```
The problem is still valid.

**Comment by chao2zhang** [comment]
This looks weird. Detekt has gradle testkit integration tests for both `com.android.library` and `com.android.application`. Your build setup appears correct.

I can try to reproduce this, but as far as I know my project is also on AGP 4.1.2 and has no problem running detekt.
Is it possible if you could try to provide a simplified sample project?

**Comment by chao2zhang** [comment]
I forgot to mention but https://github.com/cortinico/kotlin-android-template also works with detekt. It has both library and app modules.

**Comment by volsahin** [comment]
Actually problem is not detekt but how i applied it. If i choose a standard way to implement, there are no problems.
```
plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id("io.gitlab.arturbosch.detekt").version("1.16.0-RC1")
}
```
But if i choose the implementation that i mentioned in issue desc

```
plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

apply from: '../../scripts/detekt.gradle'
```
Then the problem raises. It isn't very hard to convert this into working one. But i wonder why this approach fails. This line may be the problematic one `apply plugin: io.gitlab.arturbosch.detekt.DetektPlugin`. I'll check what changed in 12.0.0

**Comment by sigis151** [comment]
I can back this up. We use the same initialization in a secondary gradle file and tried to update from 1.1.0 to 1.16.0 (I know this is a huge jump). But we used this approach because in our company we have many projects and we need to have the same detekt setup in all projects so copy-pasting files are faster and way more convenient for new project setup. 
Maybe there is another way to setup all detekt configuration and rules in a separate gradle file?

**Comment by chao2zhang** [comment]
@volsahin Could you elaborate why we need `.DetektPlugin` in `apply plugin: "io.gitlab.arturbosch.detekt.DetektPlugin"`? I am still trying to reproduce but at least `apply plugin: "io.gitlab.arturbosch.detekt.DetektPlugin"` works for me.

@sigis151 @volsahin I am also trying to find problematic commits between 1.11.1 and 1.12.0 - There are also 1.11.2 and 1.12.0-RC1, would you mind checking if those versions work or not?

**Comment by chao2zhang** [comment]
My suspicion is that we introduced android plugin configuration in 1.12.0 - https://github.com/detekt/detekt/pull/2787, which may conflict with the existing android projects setup.

**Comment by sigis151** [comment]
`1.11.1` and `1.12.0-RC1` syncs correctly and `1.12.0` fails with said error

**Comment by chao2zhang** [comment]
I guess we have verified that it is extremely likely to be broken with #2787. Would you mind sharing a sample project? I have tried to use `apply plugin` in my sample project but still couldn't reproduce.

Meanwhile, I can open a new PR to allow folks to opt-out DekteAndroid setup.

**Comment by sigis151** [comment]
fos sample I have
<details>
<summary>quality.gradle</summary>

```
buildscript {
    repositories {
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.1.0"
        classpath 'de.aaschmid:gradle-cpd-plugin:3.1'
    }
}
apply plugin: io.gitlab.arturbosch.detekt.DetektPlugin
apply plugin: 'jacoco'
apply plugin: de.aaschmid.gradle.plugins.cpd.CpdPlugin

cpd {
    language = 'kotlin'
    toolVersion = '6.26.0'
}

cpdCheck {
    minimumTokenCount = 50
    ignoreFailures = true
    source = files('src/main/kotlin', 'src/main/java')
}

detekt {
    input = files("$projectDir")
    config = files("$projectDir/config/detekt/default-detekt-config.yml")
}
dependencies {
    detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:1.1.0"
}

jacoco {
    toolVersion = "0.8.1"
    reportsDir = file("$buildDir/reports/jacoco")
}

tasks.withType(Test).whenTaskAdded {
    it.jacoco.classDumpDir = file("$project.buildDir/jacoco/dump")
}
```
</details>

And in main `app/build.gradle` at the top of it, I apply these plugins

```
apply plugin: 'com.android.application'
...
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply from: 'config/quality.gradle'
...
```

**Comment by schalkms** [comment]
@chao2zhang is this issue fixed with PR #3511? Is there anything else left to do in order to close this issue?

**Comment by cortinico** [comment]
> @chao2zhang is this issue fixed with PR #3511? Is there anything else left to do in order to close this issue?

Nope is still not solved. The root cause is applying detekt from an external build file (say `detekt.gradle`). We need to investigate why this is happening and try to come up with a solution or a workaround
