### ISSUE TITLE
NPE in DetektPomModel, probably race condition, 1.16.0-RC3

### ISSUE THREAD

**Issue by davidburstrom** [detekt/detekt#3514]
## Observed Behavior

Got the following stack trace about 50% of invocations of a closed-source tool. Happens on 1.16.0 RC2 and RC3, but not with RC1:

```
io.github.detekt.tooling.api.UnexpectedError
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:50)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:21)
        at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:26)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:25)
        ...
Caused by: java.lang.NullPointerException: Extensions.getRootArea() must not be null
        at io.github.detekt.parser.DetektPomModel.<init>(DetektPomModel.kt:24)
        at io.github.detekt.parser.KotlinEnvironmentUtilsKt.createKotlinCoreEnvironment(KotlinEnvironmentUtils.kt:56)
        at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade$environment$2.invoke(EnvironmentAware.kt:38)
        at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade$environment$2.invoke(EnvironmentAware.kt:22)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade.getEnvironment(EnvironmentAware.kt)
        at io.gitlab.arturbosch.detekt.core.ProcessingSettings.getEnvironment(ProcessingSettings.kt)
        at io.gitlab.arturbosch.detekt.core.KtTreeCompiler.<init>(KtTreeCompiler.kt:14)
        at io.gitlab.arturbosch.detekt.core.tooling.ParsingStrategyKt$inputPathsToKtFiles$1.invoke(ParsingStrategy.kt:24)
        at io.gitlab.arturbosch.detekt.core.tooling.ParsingStrategyKt$inputPathsToKtFiles$1.invoke(ParsingStrategy.kt)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$filesToAnalyze$1.invoke(Lifecycle.kt:34)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$filesToAnalyze$1.invoke(Lifecycle.kt:22)
        at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.measure(Lifecycle.kt:30)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze(Lifecycle.kt:34)
        at io.gitlab.arturbosch.detekt.core.tooling.DefaultLifecycle.analyze(Lifecycle.kt:57)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:43)
        ... 36 more
```

The tool was run in parallel with other Detekt invocations, so it could be a race condition.

## Steps to Reproduce

No steps to reproduce yet.

## Your Environment

* Version of detekt used: 1.16.0-RC2, 1.16.0-RC3
* Version of Gradle used (if applicable): 6.8.3
* Gradle scan link: N/A
* Operating System and version: macOS
* Link to your project (if it's a public repository): N/A

**Comment by davidburstromspotify** [comment]
I've tried it both with Kotlin 1.4.31 and Kotlin 1.50-M1, same error.

**Comment by davidburstrom** [comment]
Probably related problem:

```
io.github.detekt.tooling.api.UnexpectedError
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:50)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:21)
        at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:26)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:25)
       ...
Caused by: java.lang.NullPointerException
        at org.jetbrains.kotlin.com.intellij.openapi.util.KeyedExtensionCollector.getPoint(KeyedExtensionCollector.java:212)
        at org.jetbrains.kotlin.com.intellij.openapi.util.KeyedExtensionCollector.getExtensions(KeyedExtensionCollector.java:140)
        at org.jetbrains.kotlin.com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:128)
        at org.jetbrains.kotlin.com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:112)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.VirtualFileManagerImpl.getFileSystem(VirtualFileManagerImpl.java:106)
        at org.jetbrains.kotlin.cli.jvm.compiler.CoreEnvironmentUtilsKt.createSourceFilesFromSourceRoots(coreEnvironmentUtils.kt:37)
        at org.jetbrains.kotlin.cli.jvm.compiler.CoreEnvironmentUtilsKt.createSourceFilesFromSourceRoots$default(coreEnvironmentUtils.kt:34)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.createKtFiles(KotlinCoreEnvironment.kt:403)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:186)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:109)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:421)
        at io.github.detekt.parser.KotlinEnvironmentUtilsKt.createKotlinCoreEnvironment(KotlinEnvironmentUtils.kt:44)
        at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade$environment$2.invoke(EnvironmentAware.kt:38)
        at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade$environment$2.invoke(EnvironmentAware.kt:22)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade.getEnvironment(EnvironmentAware.kt)
        at io.gitlab.arturbosch.detekt.core.ProcessingSettings.getEnvironment(ProcessingSettings.kt)
        at io.gitlab.arturbosch.detekt.core.KtTreeCompiler.<init>(KtTreeCompiler.kt:14)
        at io.gitlab.arturbosch.detekt.core.tooling.ParsingStrategyKt$inputPathsToKtFiles$1.invoke(ParsingStrategy.kt:24)
        at io.gitlab.arturbosch.detekt.core.tooling.ParsingStrategyKt$inputPathsToKtFiles$1.invoke(ParsingStrategy.kt)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$filesToAnalyze$1.invoke(Lifecycle.kt:34)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$filesToAnalyze$1.invoke(Lifecycle.kt:22)
        at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.measure(Lifecycle.kt:30)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze(Lifecycle.kt:34)
        at io.gitlab.arturbosch.detekt.core.tooling.DefaultLifecycle.analyze(Lifecycle.kt:57)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:43)
        ... 36 more
```

**Comment by cortinico** [comment]
@davidburstrom I've done a small investigation and I wasn't able to find anything meaningful.
Specifically the tip of the stacktrace `DetektPomModel.kt:24`:

https://github.com/detekt/detekt/blob/4ce376e282bfff176d9b5b141462e623aab91660/detekt-parser/src/main/kotlin/io/github/detekt/parser/DetektPomModel.kt#L21-L29

is basically _copied_ from KtLint:

https://github.com/pinterest/ktlint/blob/235a414be565a49568c26f1b30d396d347efbd0f/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/KotlinPsiFileFactory.kt#L111-L121

**Comment by cortinico** [comment]
Other than adding a `.filterNotNull()` to that statement, I see little we can do 🤔

**Comment by cortinico** [comment]
After some investigation, the problem seems to be related to this:
https://youtrack.jetbrains.com/issue/IDEA-261782

Running with `-Dkotlin.environment.keepalive=true` will fix the random failures. As a more general solution, we have to wait for Kotlin 1.4.32 as described here: https://youtrack.jetbrains.com/issue/KT-45007

**Comment by davidburstrom** [comment]
@cortinico Does that mean that Detekt 1.16.0 will be blocked on that bump? I don't see anything tracking-like. There's also the possibility of unbumping Kotlin, of course.

**Comment by cortinico** [comment]
> Does that mean that Detekt 1.16.0 will be blocked on that bump?

I believe the best approach here would be revert the Kotlin bump (ping @schalkms): https://github.com/detekt/detekt/pull/3509
I suggest we release 1.16.0 stable next week with Kotlin 1.4.21 as that version of Kotlin has proven to be more stable.

**Comment by schalkms** [comment]
DONE

Sorry, I wasn't aware that a Kotlin version bump to v1.4.31 causes problems like this.

**Comment by davidburstromspotify** [comment]
Thanks @schalkms, I can confirm your revert fixed the issue!

**Comment by schalkms** [comment]
@davidburstromspotify you are welcome! 🙂
