### ISSUE TITLE
Cli argument "jvm-target" does not support values mentioned in the documentation

### ISSUE THREAD

**Issue by AlexMiroshnikov** [detekt/detekt#3551]
## Expected Behavior
Calling detekt cli with `--jvm-target JVM_11` argument (or any other "known" JVM arguments stated at https://detekt.github.io/detekt/cli.html) should not lead to failure.

## Observed Behavior
Calling detekt cli with `--jvm-target JVM_11` argument leads to failure with trace

```
java.lang.IllegalStateException: Invalid value passed to --jvm-target
	at io.gitlab.arturbosch.detekt.cli.JvmTargetConverter.convert(ArgumentConverters.kt:56)
	at io.gitlab.arturbosch.detekt.cli.JvmTargetConverter.convert(ArgumentConverters.kt:54)
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1333)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:249)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:913)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:894)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:724)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at io.gitlab.arturbosch.detekt.cli.JCommanderKt.parseArguments(JCommander.kt:15)
	at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:18)
	at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:15)
	at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:19)
```

**IMPORTANT** - it works if to pass just `11`, not `JVM_11`.

## Steps to Reproduce
Launch detekt cli with `--jvm-target` .

## Context
I am using the [github code scanning integration](https://detekt.github.io/detekt/reporting.html#integration-with-github-code-scanning) and passing the `--jvm-target` argument.

Currently the workaround is to pass `11` instead of `JVM_11`, but I believe it would be nice to either support `JVM_` prefix or make the documentation up-to-date. I would be happy to contribute in preferred way.

## Your Environment
* Version of detekt used: v1.15.0
* Link to your project (if it's a public repository): https://github.com/AlexMiroshnikov/kt-statistics/commit/a2f199e228a39135b51b191d0c8240d7646474f0#diff-1e711528da5aff1986bc49ce9f069831b1fab2a463ead8ce9c52757b31acbeb6R89

**Comment by cortinico** [comment]
I actually believe the only possible values are just `JVM_1_6` and `JVM_1_8` (from https://github.com/JetBrains/kotlin/blob/19e38bbc725ec68c9d40bc5c4ad8945266df7231/compiler/frontend.java/src/org/jetbrains/kotlin/config/JvmTarget.kt#L21-L24).

We should probably update the documentation (I'm also surprised it works with `11`).

**Comment by AlexMiroshnikov** [comment]
I think the lines we're interested in are https://github.com/JetBrains/kotlin/blob/master/compiler/config.jvm/src/org/jetbrains/kotlin/config/JvmTarget.kt#L25-L34 . There we have versions from 1.6 to 15, and I believe that's why arg `11` works fine.

**Comment by cortinico** [comment]
> There we have versions from 1.6 to 15, and I believe that's why arg `11` works fine.

Yup you're right. If you could send us a PR to update the documentation it would awesome 👌 
I've noticed we had the same problem also here: https://detekt.github.io/detekt/type-resolution.html#enabling-on-detekt-cli
