### ISSUE TITLE
GradleException: org/jetbrains/kotlin/builtins/StandardNames$FqNames

### ISSUE THREAD

**Issue by kenyee** [detekt/detekt#3573]
## Expected Behavior
Updated from Detekt 1.15 to 1.16 and got this error when running "gradle detekt"

## Observed Behavior
relevant part of stacktrace
```
Caused by: org.gradle.api.GradleException: org/jetbrains/kotlin/builtins/StandardNames$FqNames
        at io.gitlab.arturbosch.detekt.invoke.DefaultCliInvoker.invokeCli(DetektInvoker.kt:62)
        at io.gitlab.arturbosch.detekt.Detekt.check(Detekt.kt:239)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:494)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
```

## Steps to Reproduce
Gradle Version 6.8.3
Kotlin version 1.4.31
Add detekt 1.16 to build
run "gradle detekt --stacktrace"

## Context
Can't upgrade to 1.16

## Your Environment
* Version of detekt used: 1.16
* Version of Gradle used (if applicable): 6.8.3
* Gradle scan link (add `--scan` option when running the gradle task): N.A...doesn't finish so no scan
* Operating System and version: OSX
* Link to your project (if it's a public repository): N.A.

**Comment by cortinico** [comment]
Hey @kenyee 👋 

>     * N.A...doesn't finish so no scan

Which version of Java are you on? Don't you mind running `./gradlew --stop` and retrying?
Also you should be able to share a Gradle scan even if the build failed :)

**Comment by kenyee** [comment]
> Also you should be able to share a Gradle scan even if the build failed :)

ahh..didn't realize that..should have tried it :-)
https://gradle.com/s/rg4l3nzwjgeui

Java version is 
➜  java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

It also fails in our CI which is running pretty plain OpenJDK8 on Centos so I don't think it's because I'm using JDK11.

**Comment by kenyee** [comment]
might need this link instead: https://scans.gradle.com/s/rg4l3nzwjgeui

**Comment by chao2zhang** [comment]
You seem to have inconsistent versions (1.4.10 vs 1.4.30) for plugins in your project:
```
org.jetbrains.kotlin.jvm | 1.4.10 | 1 usage | org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapper |  
-- | -- | -- | -- | --
  | org.jetbrains.kotlin.plugin.allopen | 1.4.30 | 1 usage | org.jetbrains.kotlin.allopen.gradle.AllOpenGradleSubplugin |  
  | org.jetbrains.kotlin.plugin.scripting | 1.4.10 | 1 usage | org.jetbrains.kotlin.gradle.scripting.internal.ScriptingGradleSubplugin |  
  | org.jetbrains.kotlin.plugin.spring | 1.4.30 | 1 usage | org.jetbrains.kotlin.allopen.gradle.SpringGradleSubplugin
```

**Comment by kenyee** [comment]
https://scans.gradle.com/s/56gyz425dwolu/plugins

Fixed...was specifying this to match the Kotlin version:
id 'org.jetbrains.kotlin.plugin.spring' version '1.4.10'

same error as before...

**Comment by chao2zhang** [comment]
I think there are two things we could try:
- 1. Disable `UseIsNullOrEmpty`, since this is the culprit rule.
- 2. Try with upgrade Kotlin to 1.4.21, because detekt 1.16.0 is shipped with this Kotlin version (https://github.com/detekt/detekt/pull/3521/)

**Comment by kenyee** [comment]
Can't switch to 1.4.21 because Spring released w/ 1.4.10 :-(
I'll try disabling that other rule...might be worth adding a try/catch for this in the Detekt code too if it works?

**Comment by chao2zhang** [comment]
Yeah that's a good suggestion. I think checkstyle has this behavior to catch exceptions if it is thrown inside each rule.

**Comment by kenyee** [comment]
Following up on this.  I upgraded to 0.16.0.  Then ran detektGenerateConfig to create a new config and the detekt.yaml already has it turned off by default:
  UseIsNullOrEmpty:
    active: false

Ran detekt and get the same error so it seems like it's turned off by default...but causes an error w/ Kotlin 1.4.10 still.

**Comment by chao2zhang** [comment]
https://github.com/detekt/detekt/pull/3585 may help to resolve the problem: When the rule has `active: false`, it should not instantiate the rule.
