### ISSUE TITLE
org.gradle.api.internal.initialization.DefaultClassLoaderScope must be locked before it can be used to compute a classpath!

### ISSUE THREAD

**Issue by lhmoraes** [detekt/detekt#3833]
```
java.lang.IllegalArgumentException: org.gradle.api.internal.initialization.DefaultClassLoaderScope@4f0bab40 must be locked before it can be used to compute a classpath!
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider.exportClassPathFromHierarchyOf(KotlinScriptClassPathProvider.kt:151)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider.computeCompilationClassPath(KotlinScriptClassPathProvider.kt:147)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider.access$computeCompilationClassPath(KotlinScriptClassPathProvider.kt:95)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider$compilationClassPathOf$1.invoke(KotlinScriptClassPathProvider.kt:143)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider$compilationClassPathOf$1.invoke(KotlinScriptClassPathProvider.kt:95)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProviderKt$sam$java_util_function_Function$0.apply(KotlinScriptClassPathProvider.kt)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider.compilationClassPathOf(KotlinScriptClassPathProvider.kt:143)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.compilationClassPathOf(KotlinScriptEvaluator.kt:265)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.evaluateSecondStageOf(Interpreter.kt:397)
	at Program.execute(Unknown Source)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:501)
	at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:178)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:124)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:51)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:36)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:34)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
```

##  Environment
* Version of detekt used: 1.17.1
* Version of Gradle used:  6.8.3
* Kotlin Version: 1.5
* Java Version: 11
* Operating System and version: macOS Big Sur Version 11.3.1
* Spring Boot 2.5 Multi Module Project

**Comment by cortinico** [comment]
Can you provide more context?
When is this happening?
Also I don't see any references to Detekt in the stacktrace 🤔

**Comment by lhmoraes** [comment]
Hi @cortinico if I add the **Detekt** plugin to me **build.gradle.kts** I started to get the error below, without Detekt the build works fine. I will setup a simple project and do a try (without multi-modules)

`id("io.gitlab.arturbosch.detekt") version "1.17.1"`

_`java.lang.IllegalArgumentException: org.gradle.api.internal.initialization.DefaultClassLoaderScope@1130c284 must be locked before it can be used to compute a classpath!`_

Thanks

**Comment by lhmoraes** [comment]
I setup a simple Spring Boot application and Detekt worked, I've used the the same dependencies and plugins version from the multi-module app. So, looks like the issue is related with my multi-module configuration

**Comment by lhmoraes** [comment]
Hi @cortinico it's fixed, the issue was related with my multi-module configuration

Thanks for your help

**Comment by cortinico** [comment]
Awesome thanks for the follow up
