### ISSUE TITLE
HtmlReport error in rule: TooManyFunctions

### ISSUE THREAD

**Issue by winchances** [detekt/detekt#3839]
I found an error in the html report:
- Rule: TooManyFunctions
- Detekt version: 1.16.0
- Stacktrace:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 5
	at java.lang.String.substring(String.java:1963)
	at io.github.detekt.report.html.HtmlUtilsKt.writeErrorLine(HtmlUtils.kt:51)
	at io.github.detekt.report.html.HtmlUtilsKt.access$writeErrorLine(HtmlUtils.kt:1)
	at io.github.detekt.report.html.HtmlUtilsKt.snippetCode(HtmlUtils.kt:35)
	at io.github.detekt.report.html.HtmlOutputReport.renderFinding(HtmlOutputReport.kt:148)
```
- How to reproduce it: <WRITE HERE HOW TO REPRODUCE THIS ISSUE. A CODE SNIPPET IS THE BEST WAY.>

**Comment by cortinico** [comment]
> Detekt version: 1.16.0

Can you please update to `1.17.1` and try again?

> How to reproduce it:

Can you please provide a way to reproduce this?

**Comment by schalkms** [comment]
Unfortunately, this issue can't be reproduced without the corresponding code snippet. Without the given information, there's not much we can do here. Hence, I'm  closing until a reproducer is available.
