### ISSUE TITLE
class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by tateisu** [detekt/detekt#3884]
```
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in
module java.base of loader 'bootstrap')
        at io.gitlab.arturbosch.detekt.api.ConfigAware$DefaultImpls.getActive(ConfigAware.kt:48)
        at io.gitlab.arturbosch.detekt.api.Rule.getActive(Rule.kt:20)
        at io.gitlab.arturbosch.detekt.api.Rule.visitCondition(Rule.kt:61)
        at io.gitlab.arturbosch.detekt.api.internal.BaseRule.visitFile(BaseRule.kt:49)
        at io.gitlab.arturbosch.detekt.core.Analyzer$analyze$4.invoke(Analyzer.kt:121)
        at io.gitlab.arturbosch.detekt.core.Analyzer.analyze(Analyzer.kt:133)
        at io.gitlab.arturbosch.detekt.core.Analyzer.runSync(Analyzer.kt:68)
        ... 147 more
```

## Expected Behavior
it's caused by miss typing of "true", but the app might show about the place of error congiguration?

## Your Environment

```
Running detekt '1.17.1' on Java '14.0.1+8' on OS 'Windows 10'
Gradle: gradle-6.9-bin.zip
Android Studio 4.2.1
Build #AI-202.7660.26.42.7351085, built on May 11, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 24
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.dubreuia, com.notime.intellijPlugin.backgroundImagePlus, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets
```

- Gradle Scan Link https://gradle.com/s/qv27lp2jznzmw
- Link to your project https://github.com/tateisu/SubwayTooter

**Comment by cortinico** [comment]
> it's caused by miss typing of "true", but the app might show about the place of error congiguration?

Yes that might be the case.

Sadly I'm unable to reproduce your issue. Seems like detekt is not configured in the project you linked?

**Comment by tateisu** [comment]
generate config , then modify `active: tru` (missing `e`) to reproduce it.

**Comment by marschwar** [comment]
I do know how to reproduce it, but the only way I could fix it, was to add a check to the config validation phase which is not ideal. The underlying problem is type erasure and I have no idea how this could be solved without reified types. The smallest possible reproducer I could come up with:

```kotlin
describe("due to type erasure") {
    it("throws ClassCastException") {
        fun <T : Any> bar(): T? {
            return "bar" as? T
        }
        val foo: Boolean = bar() ?: false

        assertThat(foo).isFalse()
    }
}
```

**Comment by tateisu** [comment]
Is it mandatory to detect it during the configuration validation phase?

In this case the help for the users is that the rule name and property name of the relevant part are included in the error message. How about just adding an error message to the cast exception in the part that gets the value?

for example, changing this method
https://github.com/detekt/detekt/blob/4a89a25c82d35874571270fa1ff32751f2f268a1/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/ConfigAware.kt#L64

before
```
override fun <T : Any> valueOrDefault(key: String, default: T): T =
    ruleConfig.valueOrDefault(key, default)
```

after
```
override fun <T : Any> valueOrDefault(key: String, default: T): T =
    try{
        ruleConfig.valueOrDefault(key, default)
    }catch(ex: ClassCastException){
        throw SomethingException("Can't get value of $ruleId.$key as ${(default as Any).javaClass.simpleName}",ex)
    }
```

**Comment by marschwar** [comment]
I agree that catching the exception and raising an error with a meaningful message is the only way. Would you like to open a PR for this? 

If so, please have a look at `BaseConfig.kt`. There already is code that works very similarly. May I suggest creating a function `fun <T : Any> Config.valueOrNullInternal` to do the type checking and the error handling?

**Comment by marschwar** [comment]
I tried to make the change, but it did not have the effect I was hoping for. The `ClassCastException` is thrown in the `ConfigAware` default implementation bypassing the catch clause. This makes sense but is rather annoying.

```
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
	at io.gitlab.arturbosch.detekt.api.ConfigAware$DefaultImpls.getActive(ConfigAware.kt:48)
	at io.gitlab.arturbosch.detekt.api.Rule.getActive(Rule.kt:20)
	at io.gitlab.arturbosch.detekt.api.Rule.visitCondition(Rule.kt:61)
	at io.gitlab.arturbosch.detekt.api.internal.BaseRule.visitFile(BaseRule.kt:49)
```

**Comment by tateisu** [comment]
I thought the stack trace I wrote in the issue wasn't enough, so I tried again using cli-all.jar instead of via Gradle.

```
$ java -jar detekt-cli-1.17.1-all.jar -c config/detekt/detekt.yml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.ReflectionUtil (file:/Z:/20210630TestDetekt
/detekt-cli-1.17.1-all.jar) to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.IllegalStateException: Analyzing Z:\20210630TestDetekt\src\main\kotlin\Main.kt led to an exception.
The original exception message was: Value "tru" set for config parameter "empty-blocks > EmptyClassBlock > active" is no
t of required type Boolean.
Running detekt '1.17.1' on Java '14.0.1+8' on OS 'Windows 10'
If the exception message does not help, please feel free to create an issue on our GitHub page.
        at io.gitlab.arturbosch.detekt.core.AnalyzerKt.throwIllegalStateException(Analyzer.kt:152)
        at io.gitlab.arturbosch.detekt.core.AnalyzerKt.access$throwIllegalStateException(Analyzer.kt:1)
        at io.gitlab.arturbosch.detekt.core.Analyzer.runSync(Analyzer.kt:69)
        at io.gitlab.arturbosch.detekt.core.Analyzer.run(Analyzer.kt:51)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$result$1.invoke(Lifecycle.kt:43)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$result$1.invoke(Lifecycle.kt:22)
        at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.measure(Lifecycle.kt:30)
        at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze(Lifecycle.kt:40)
        at io.gitlab.arturbosch.detekt.core.tooling.DefaultLifecycle.analyze(Lifecycle.kt:57)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:43)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:21)
        at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBr
idge.kt:26)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:25)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.call(Runner.kt:33)
        at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:33)
        at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:15)
        at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:19)
Caused by: java.lang.IllegalStateException: Value "tru" set for config parameter "empty-blocks > EmptyClassBlock > activ
e" is not of required type Boolean.
        at io.gitlab.arturbosch.detekt.core.config.BaseConfigKt.valueOrDefaultInternal(BaseConfig.kt:29)
        at io.gitlab.arturbosch.detekt.core.config.BaseConfigKt.valueOrDefaultInternal$default(BaseConfig.kt:15)
        at io.gitlab.arturbosch.detekt.core.config.YamlConfig.valueOrDefault(YamlConfig.kt:32)
        at io.gitlab.arturbosch.detekt.core.config.DisabledAutoCorrectConfig.valueOrDefault(DisabledAutoCorrectConfig.kt
:13)
        at io.gitlab.arturbosch.detekt.api.ConfigAware$DefaultImpls.valueOrDefault(ConfigAware.kt:65)
        at io.gitlab.arturbosch.detekt.api.Rule.valueOrDefault(Rule.kt:20)
        at io.gitlab.arturbosch.detekt.api.ConfigAware$DefaultImpls.getActive(ConfigAware.kt:48)
        at io.gitlab.arturbosch.detekt.api.Rule.getActive(Rule.kt:20)
        at io.gitlab.arturbosch.detekt.api.Rule.visitCondition(Rule.kt:61)
        at io.gitlab.arturbosch.detekt.api.MultiRule.preVisit(MultiRule.kt:19)
        at io.gitlab.arturbosch.detekt.api.internal.BaseRule.visitFile(BaseRule.kt:50)
        at io.gitlab.arturbosch.detekt.core.Analyzer$analyze$4.invoke(Analyzer.kt:121)
        at io.gitlab.arturbosch.detekt.core.Analyzer.analyze(Analyzer.kt:133)
        at io.gitlab.arturbosch.detekt.core.Analyzer.runSync(Analyzer.kt:68)
```

**Comment by tateisu** [comment]
The output in above is the expected behavior.

There seems to be a necessary condition to output the error output mentioned in the issue.
Android Studio? No, it happened even when I incorporated the Gradle Plugin into a test project created with IntelliJ IDEA.

```
kotlin 1.5.20
detekt 1.17.1

IntelliJ IDEA 2021.1.2 (Community Edition)
Build #IC-211.7442.40, built on June 1, 2021
Runtime version: 11.0.11+9-b1341.57 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3959M
Cores: 24
Non-Bundled Plugins: com.notime.intellijPlugin.backgroundImagePlus (1.0.3), org.jetbrains.kotlin (211-1.5.20-release-284-IJ7442.40), izhangzhihao.rainbow.brackets (6.18)
Kotlin: 211-1.5.20-release-284-IJ7442.40
```

```
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
        at io.gitlab.arturbosch.detekt.api.ConfigAware$DefaultImpls.getActive(ConfigAware.kt:48)
        at io.gitlab.arturbosch.detekt.api.Rule.getActive(Rule.kt:20)
        at io.gitlab.arturbosch.detekt.api.Rule.visitCondition(Rule.kt:61)
        at io.gitlab.arturbosch.detekt.api.MultiRule.preVisit(MultiRule.kt:19)
        at io.gitlab.arturbosch.detekt.api.internal.BaseRule.visitFile(BaseRule.kt:50)
        at io.gitlab.arturbosch.detekt.core.Analyzer$analyze$4.invoke(Analyzer.kt:121)
        at io.gitlab.arturbosch.detekt.core.Analyzer.analyze(Analyzer.kt:133)
        at io.gitlab.arturbosch.detekt.core.Analyzer.runSync(Analyzer.kt:68)
```

**Comment by cortinico** [comment]
> No, it happened even when I incorporated the Gradle Plugin into a test project created with IntelliJ IDEA.

@marschwar Do you have any hunch on why the CLI behavior might be different from the Gradle Plugin?

**Comment by marschwar** [comment]
Let me look into it

**Comment by marschwar** [comment]
The culprit seems to be the `--build-upon-default-config` flag or more accurately the `CompositeConfig`.

```kotlin
override fun <T : Any> valueOrDefault(key: String, default: T): T =
    lookFirst.valueOrNull(key) ?: lookSecond.valueOrDefault(key, default)

override fun <T : Any> valueOrNull(key: String): T? =
    lookFirst.valueOrNull(key) ?: lookSecond.valueOrNull(key)
```

As stated [above](https://github.com/detekt/detekt/issues/3884#issuecomment-869951737), `valueOrNull` will return a String if it is not a proper Boolean which will cause the `ClassCastException` in the field initializer.
