### ISSUE TITLE
Please add simple run detekt by cli

### ISSUE THREAD

**Issue by patsevanton** [detekt/detekt#3914]
I try run detekt by cli

```
java -jar detekt-cli-1.17.1-all.jar -p /home/apatsev/github/admin/
Exception in thread "main" java.lang.IllegalArgumentException: Given plugin ‘/home/apatsev/github/admin’ is not a JAR.
        at io.gitlab.arturbosch.detekt.core.settings.ExtensionFacade.<init>(ClassloaderAware.kt:23)
        at io.gitlab.arturbosch.detekt.core.ProcessingSettings.<init>(ProcessingSettings.kt:36)
        at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt$withSettings$settings$1.invoke(ProcessingSpecSettingsBridge.kt:18)
        at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt$withSettings$settings$1.invoke(ProcessingSpecSettingsBridge.kt)
        at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:17)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:42)
        at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:25)
        at io.gitlab.arturbosch.detekt.cli.runners.Runner.call(Runner.kt:33)
        at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:33)
        at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:15)
        at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:19)
```

Please add simple run detekt by cli

**Comment by arhont375** [comment]
You can find example of command line usage here: https://detekt.github.io/detekt/cli.html#any-os

**Comment by cortinico** [comment]
> java -jar detekt-cli-1.17.1-all.jar -p /home/apatsev/github/admin/

Also you're specifying `-p` that is for adding external plugins, but I suppose you wanted to use `-i` (`--input`) to specify the path to analyse.

**Comment by patsevanton** [comment]
Thanks!
