### ISSUE TITLE
TrailingComma auto correct crashes in Detekt but not ktlint

### ISSUE THREAD

**Issue by gpeal** [detekt/detekt#4489]
## Expected Behavior
Detekt can auto-correct missing trailing commas.

## Observed Behavior
Detekt crashes when auto-correcting missing trailing commas. However, running the same codebase through ktlint directly works fine and removing trailing commas seems to be fine.

```
Missing extension point: org.jetbrains.kotlin.com.intellij.treeCopyHandler in container org.jetbrains.kotlin.com.intellij.core.CoreApplicationEnvironment$1@1d2686a8
java.lang.IllegalArgumentException: Missing extension point: org.jetbrains.kotlin.com.intellij.treeCopyHandler in container org.jetbrains.kotlin.com.intellij.core.CoreApplicationEnvironment$1@1d2686a8
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:273)
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.BaseExtensionPointName.getPointImpl(BaseExtensionPointName.java:28)
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:42)
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.encodeInformation(ChangeUtil.java:43)
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.lambda$encodeInformation$0(ChangeUtil.java:39)
	at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:567)
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.encodeInformation(ChangeUtil.java:39)
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.copyElement(ChangeUtil.java:95)
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.copyElement(ChangeUtil.java:87)
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.generateTreeElement(ChangeUtil.java:131)
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.ChangeUtil.copyToElement(ChangeUtil.java:113)
	at org.jetbrains.kotlin.com.intellij.extapi.psi.ASTDelegatePsiElement.addAfter(ASTDelegatePsiElement.java:292)
	at com.pinterest.ktlint.ruleset.experimental.trailingcomma.TrailingCommaRule.reportAndCorrectTrailingCommaNodeBefore(TrailingCommaRule.kt:228)
	at com.pinterest.ktlint.ruleset.experimental.trailingcomma.TrailingCommaRule.visitValueList(TrailingCommaRule.kt:138)
	at com.pinterest.ktlint.ruleset.experimental.trailingcomma.TrailingCommaRule.visit(TrailingCommaRule.kt:63)
	at io.gitlab.arturbosch.detekt.formatting.FormattingRule.apply(FormattingRule.kt:80)
	at io.gitlab.arturbosch.detekt.formatting.TestFilesKt$lint$1.invoke(TestFiles.kt:16)
	at io.gitlab.arturbosch.detekt.formatting.TestFilesKt$lint$1.invoke(TestFiles.kt:16)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:229)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230)
	at io.gitlab.arturbosch.detekt.formatting.TestFilesKt.lint(TestFiles.kt:16)
	at io.gitlab.arturbosch.detekt.formatting.TestFilesKt.lint$default(TestFiles.kt:13)
	at io.gitlab.arturbosch.detekt.formatting.TrailingCommaSpec$1$1$1.invoke(TrailingCommaSpec.kt:30)
	at io.gitlab.arturbosch.detekt.formatting.TrailingCommaSpec$1$1$1.invoke(TrailingCommaSpec.kt:22)
```

## Steps to Reproduce
Add `Config.AUTO_CORRECT_KEY to true` to the config for [TrailingCommaSpec](https://github.com/detekt/detekt/blob/main/detekt-formatting/src/test/kotlin/io/gitlab/arturbosch/detekt/formatting/TrailingCommaSpec.kt#L79) and run the test. I was able to reproduce the crash on my computer

## Your Environment
* Version of detekt used: Tip of tree (56e7fa94a)
* Gradle scan link (add `--scan` option when running the gradle task): N/A was able to repro with Spek test
* Operating System and version: macOS 12.1 M1 Pro w/ Zulu Apple Silicon openJDK and popOS AMD.
* Link to your project (if it's a public repository): N/A was able to repro with Spek test

**Comment by gpeal** [comment]
@BraisGabin FYI, I originally thought this was Apple Silicon specific but upon testing further, it is not. The reproduction steps are very simple and listed in the description.

**Comment by BraisGabin** [comment]
Yes, I could reproduce it on my laptop (no M1). But I don't know what's going on here.

**Comment by cortinico** [comment]
> But I don't know what's going on here.

I've spent some time investigating this. That's essentially another instance of #4003
I'll send a PR shortly.
