### ISSUE TITLE
Unable to compile code snippets with `KotlinScriptEngine` repeatedly

### ISSUE THREAD

**Issue by marschwar** [detekt/detekt#4535]
related to [work on the migration to junit](https://github.com/detekt/detekt/pull/4523#issuecomment-1021062680).

## Observed Behavior
Running all tests with snippet compilation fails with a compiler exception.

```
IgnoredReturnValueSpec > default config with annotated return values > does not report when a function's return value is used in a test statement() FAILED
    org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration Line_18
    File being compiled: (2,35) in /Line_18.kts
    The root cause org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException was thrown at: org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18)
        at app//org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitDeclaration(ExceptionWrappingKtVisitorVoid.kt:43)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:457)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitDeclaration(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtVisitor.visitScript(KtVisitor.java:78)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:73)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:523)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtScript.accept(KtScript.java:69)
        at app//org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.registerDeclarations(LazyTopDownAnalyzer.kt:80)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.visitKtFile(LazyTopDownAnalyzer.kt:98)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:517)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:245)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:232)
        at app//org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitElement(ExceptionWrappingKtVisitorVoid.kt:27)
        at app//org.jetbrains.kotlin.com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
        at app//org.jetbrains.kotlin.psi.KtVisitor.visitKtFile(KtVisitor.java:73)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:69)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:517)
        at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:245)
        at app//org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:232)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:203)
        at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:58)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.ReplCodeAnalyzerBase.runAnalyzer(ReplCodeAnalyzer.kt:127)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.ReplCodeAnalyzerBase.doAnalyze(ReplCodeAnalyzer.kt:136)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.ReplCodeAnalyzerBase.analyzeReplLine(ReplCodeAnalyzer.kt:109)
        at app//org.jetbrains.kotlin.scripting.compiler.plugin.repl.GenericReplCompiler.compile(GenericReplCompiler.kt:81)
        at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:72)
        at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compile(KotlinScriptEngine.kt:18)
        at app//io.gitlab.arturbosch.detekt.test.RuleExtensionsKt.compileAndLintWithContext(RuleExtensions.kt:60)
        at app//io.gitlab.arturbosch.detekt.rules.bugs.IgnoredReturnValueSpec$default config with annotated return values.does not report when a function's return value is used in a test statement(IgnoredReturnValueSpec.kt:436)

        Caused by:
        org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException: Descriptor wasn't found for declaration SCRIPT
            at app//org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:18)
            at app//org.jetbrains.kotlin.resolve.lazy.BasicAbsentDescriptorHandler.diagnoseDescriptorNotFound(AbsentDescriptorHandler.kt:17)
            at app//org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.findClassDescriptor(LazyDeclarationResolver.kt:88)
            at app//org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.getScriptDescriptor(LazyDeclarationResolver.kt:65)
            at app//org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer$analyzeDeclarations$1.visitScript(LazyTopDownAnalyzer.kt:91)
            at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:523)
            at app//org.jetbrains.kotlin.psi.KtVisitorVoid.visitScript(KtVisitorVoid.java:21)
            at app//org.jetbrains.kotlin.psi.KtScript.accept(KtScript.java:69)
            at app//org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:49)
            at app//org.jetbrains.kotlin.resolve.ExceptionWrappingKtVisitorVoid.visitDeclaration(ExceptionWrappingKtVisitorVoid.kt:32)
            ... 33 more
```
## Steps to Reproduce
`./gradlew test -x :detekt-gradle-plugin:test -Pcompile-test-snippets=true --rerun-tasks`.

**Comment by marschwar** [comment]
Can someone please explain why the `io.gitlab.arturbosch.detekt.test.RuleExtensions.kt` defines 

```kotlin
fun BaseRule.lint(content: String): List<Finding>
fun BaseRule.lintWithContext(environment: KotlinCoreEnvironment, content: String, vararg additionalContents: String): List<Finding>

fun BaseRule.compileAndLint(content: String): List<Finding>
fun BaseRule.compileAndLintWithContext(environment: KotlinCoreEnvironment, content: String): List<Finding>
```

Both versions seem to be used by tests but I cannot seem to find a pattern.

**Comment by BraisGabin** [comment]
We have both because there are some snippets that is know that doesn't compile, but we want to have them there anyway. Maybe we could simplify those to one with a default value of `checkSnippetCompile` and allow the caller to set it to `false` to be more explicit.

**Comment by schalkms** [comment]
I think I can explain this issue. In fact, I already wrote a comment in a PR or issue that I can't find quickly at the moment.
Nevertheless, as far as I can tell, this issue happens when compiled snippets in a test class use the same class or function name all over the place. As a workaround, one can just use different class or function names fitting to the use case under test. This usually solved those weird problems.

**Comment by marschwar** [comment]
Oh thank you. That makes total sense. I was going crazy over this. So the same underlying Script engine can be reused as long as there is no conflict in names.

**Comment by BraisGabin** [comment]
Does it have sense to instantiate one script per snippet? Or would it be too slow? Junit runs the tests in an undefined order so the old way to workaround this could not work as well.

**Comment by schalkms** [comment]
> So the same underlying Script engine can be reused as long as there is no conflict in names.

@marschwar This conclusion is a bit too simple. Please take a look at the modified PR #4536. With 2 repeated tests runs everything works fine. 

I don't know the exact threshold at which conflicting names cause problems with the underlying script engine. It's fair to say that detekt's tests heavily depend on the script engine. I don't think that the script engine is designed to handle many conflicting names at subsequent compiles.

**Comment by BraisGabin** [comment]
The engine uses 8 different instances, isn't it? So running it twice you are not repeating any instance.

**Comment by BraisGabin** [comment]
<img width="339" alt="Captura de pantalla 2022-01-28 a las 18 10 22" src="https://user-images.githubusercontent.com/721244/151591142-e341d802-a5fa-4b57-aa36-4f720d1dd68f.png">

https://github.com/detekt/detekt/blob/4a89a25c82d35874571270fa1ff32751f2f268a1/detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt#L13

☝️ this line makes that the first 8 runs "work" and then the other ones doesn't. I imagine that this bug was difficult to hit because even if you have the same code twice you will hit another compiler so it would work.

I'm going to benchmark how bad is to create the compiler each time.

**Comment by schalkms** [comment]
Yes, that's true. I forgot that detekt has 8 script engines running in parallel.

**Comment by BraisGabin** [comment]
I wanted to check what happen if instead of cache them we use a fresh one each time. Now I know what happen: `OutOfMemmory`. I don't know how to avoid that `OutOfMemmory` because `KotlinJsr223JvmLocalScriptEngine` doesn't have any `close()` or similar function to call after you use it so it should be ok to let the GC to do the work... but it's not.

**Comment by marschwar** [comment]
I was going to implement a Pool that recovers automatically

**Comment by schalkms** [comment]
@BraisGabin the performance impact is huge. Tests last way longer if every test creates it's own script engine. Even if there were no `OutOfMemory` problem, it wouldn't be feasible.

@marschwar but detekt does have a pool in place? What do you want to change? I'm curious.
https://github.com/detekt/detekt/blob/main/detekt-test-utils/src/main/kotlin/io/github/detekt/test/utils/KotlinScriptEnginePool.kt

**Comment by BraisGabin** [comment]
> I was going to implement a Pool that recovers automatically

That could work. Try/catch that type of error, recover and re-run, if it fails a second time let it crash.

**Comment by marschwar** [comment]
I created a pool that

a) retries with a fresh script engine instance in case of a name clash
b) allows the pool of engines to grow dynamically
c) synchronizes access to the underlying script engines
