### ISSUE TITLE
NoSuchElementException after updating to 1.20.0-RC1

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#4604]
Just tried out 1.20.0-RC1 and got a few of these exceptions:

```
java.lang.IllegalStateException: Analyzing /home/eli/workspace/myapp/app/src/main/kotlin/co/app/common/AppInfo.kt led to an exception. 
  The original exception message was: java.util.NoSuchElementException: Sequence contains no element matching the predicate.
  Running detekt '1.20.0-RC1' on Java '17.0.2+8-LTS' on OS 'Linux'
```

Here is `AppInfo.kt`:

```
package co.app.common

import co.app.coroutines.flow.conflatedSharedFlow
import kotlinx.coroutines.flow.first

interface AppInfo {
  val versionName: String
  val versionCode: Int

  val playStorePackage: String

  val osVersion: Int

  val appVersion: String

  var suggestedVersion: String?
  suspend fun awaitSuggestedVersionChanged(): String

  fun isAppBelowSuggestedVersion(suggestedVersion: String?): Boolean
}

internal class AppInfoImpl(
  appVersionName: String,
  appVersionCode: Int,
  appPackageName: String,
  currentOsVersion: Int
) : AppInfo {
  override val versionName = appVersionName

  override val versionCode = appVersionCode

  override val playStorePackage = appPackageName

  override val osVersion = currentOsVersion

  override val appVersion = "a${versionName.removeSuffix("-DEBUG")}.0"

  private val suggestedVersionFlow = conflatedSharedFlow<String>()

  override var suggestedVersion: String? = null
    set(value) {
      field = value
      if(value != null) {
        suggestedVersionFlow.tryEmit(value)
      }
    }

  override suspend fun awaitSuggestedVersionChanged(): String = suggestedVersionFlow.first()

  override fun isAppBelowSuggestedVersion(suggestedVersion: String?): Boolean {
    tailrec fun isAppBelowSuggested(current: List<Int>, suggested: List<Int>, index: Int): Boolean =
      when {
        index >= current.size -> false

        current[index] != suggested[index] -> current[index] < suggested[index]

        else -> isAppBelowSuggested(current, suggested, index + 1)
      }

    return suggestedVersion?.let {
      val currentVersion = versionName.removeSuffix("-DEBUG")

      when(suggestedVersion) {
        currentVersion -> false

        else -> {
          val currentVersionSplit = currentVersion.split(".").mapNotNull { it.toIntOrNull() }
          val suggestedVersionSplit = suggestedVersion.split(".").mapNotNull { it.toIntOrNull() }

          when {
            currentVersionSplit.size != 3 || suggestedVersionSplit.size != 3 -> false

            else -> isAppBelowSuggested(currentVersionSplit, suggestedVersionSplit, index = 0)
          }
        }
      }
    } ?: false
  }
}

```

**Comment by BraisGabin** [comment]
Do you have the stacktrace?

**Comment by eygraber** [comment]
```
Caused by: java.util.NoSuchElementException: Sequence contains no element matching the predicate.
        at com.pinterest.ktlint.ruleset.experimental.trailingcomma.TrailingCommaRule.visitValueList(TrailingCommaRule.kt:357)
        at com.pinterest.ktlint.ruleset.experimental.trailingcomma.TrailingCommaRule.visit(TrailingCommaRule.kt:61)
        at io.gitlab.arturbosch.detekt.formatting.FormattingRule.apply(FormattingRule.kt:80)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2.invoke(KtLintMultiRule.kt:114)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2.invoke(KtLintMultiRule.kt:113)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visitTokens(KtLintMultiRule.kt:142)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visitTokens(KtLintMultiRule.kt:144)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visitTokens(KtLintMultiRule.kt:144)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visitTokens(KtLintMultiRule.kt:144)
        at io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visit(KtLintMultiRule.kt:113)
        at io.gitlab.arturbosch.detekt.api.BaseRule.visitFile(BaseRule.kt:46)
        at io.gitlab.arturbosch.detekt.core.Analyzer.analyze$executeRules(Analyzer.kt:122)
        at io.gitlab.arturbosch.detekt.core.Analyzer.analyze(Analyzer.kt:133)
        at io.gitlab.arturbosch.detekt.core.Analyzer.access$analyze(Analyzer.kt:31)
        at io.gitlab.arturbosch.detekt.core.Analyzer$runAsync$tasks$1$1.invoke(Analyzer.kt:85)
        at io.gitlab.arturbosch.detekt.core.Analyzer$runAsync$tasks$1$1.invoke(Analyzer.kt:83)
        at io.gitlab.arturbosch.detekt.core.TaskPoolKt.task$lambda-0(TaskPool.kt:12)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)

```

**Comment by eygraber** [comment]
https://github.com/detekt/detekt/issues/2398#issuecomment-1011392672

**Comment by cortinico** [comment]
Yup we'll have to do https://github.com/detekt/detekt/pull/4584 this manually and make sure it lands inside 1.20.0

**Comment by BraisGabin** [comment]
I think that we can close this now that #4630 is merged
