### ISSUE TITLE
generateDocumentation fails when there is @throw in the noncompliant block

### ISSUE THREAD

**Issue by atulgpt** [detekt/detekt#5667]
## Expected Behavior
While writing `@throws` before function, in either `noncompliant` or `compliant` block should not fail the `./gradlew generateDocumentation` command

## Observed Behavior
`./gradlew generateDocumentation`  fails with the below stack trace when there is mention of `@throws` in `noncompliant` or `compliant` block

Gradle Stacktrace
```txt
Exception in thread "main" io.gitlab.arturbosch.detekt.generator.collection.exception.InvalidCodeExampleDocumentationException: Invalid rule documentation for noncompliant and compliant code examples in Rule SuspendFunInsideRunCatching contains an incorrect noncompliant code definition.
        at io.gitlab.arturbosch.detekt.generator.collection.DocumentationCollector.extractNonCompliantDocumentation(DocumentationCollector.kt:43)
        at io.gitlab.arturbosch.detekt.generator.collection.DocumentationCollector.extractRuleDocumentation(DocumentationCollector.kt:30)
        at io.gitlab.arturbosch.detekt.generator.collection.DocumentationCollector.setClass(DocumentationCollector.kt:22)
        at io.gitlab.arturbosch.detekt.generator.collection.RuleVisitor.visitClassOrObject(RuleVisitor.kt:112)
```

## Steps to Reproduce
Comment used to repro the scenario with the above crash
```
/**
 *
 * <noncompliant>
 * @Throws
 * </noncompliant>
 *
 * <compliant>
 *
 * </compliant>
 *
 */
```

## Context
 Not able to use `@Throws(IllegalStateException::class)` while describing a method in these blocks

**Comment by BraisGabin** [comment]
Did you try with `@@Throws`? `@` is a special character on kdoc. For that reason we have `@@` ss a way to scape it.

**Comment by atulgpt** [comment]
Hi @BraisGabin yes 😅. I forgot the escaping. Sorry for the false alarm
