### ISSUE TITLE
`SuspendFunWithCoroutineScopeReceiverSpec` has non compiling code in TCs

### ISSUE THREAD

**Issue by atulgpt** [detekt/detekt#5715]
## Expected Behavior
Running `./gradlew test -Pcompile-test-snippets=true` should compile for `detekt` project

## Observed Behavior
It is failing as `SuspendFunWithCoroutineScopeReceiverSpec` has test cases where the code doesn't compile.

## Steps to Reproduce
Run `./gradlew test -Pcompile-test-snippets=true` then build fails due below errors
```
SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > no reports when suspend function has no receiver() FAILED
    io.github.detekt.test.utils.KotlinScriptException: Given Kotlin code is invalid.
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:37)
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compile(KotlinScriptEngine.kt:23)
        at app//io.gitlab.arturbosch.detekt.test.RuleExtensionsKt.compileAndLintWithContext(RuleExtensions.kt:59)
        at app//io.gitlab.arturbosch.detekt.rules.coroutines.SuspendFunWithCoroutineScopeReceiverSpec$SuspendFunWithCoroutineScopeReceiver rule.no reports when suspend function has no receiver(SuspendFunWithCoroutineScopeReceiverSpec.kt:111)

        Caused by:
        javax.script.ScriptException: Error: error: unresolved reference: launch
            launch {
            ^
        error: suspension functions can be called only within coroutine body
                delay(timeMillis = 1000)
                ^
            at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:74)
            at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
            at app//io.github.detekt.test.utils.PooledScriptEngine.compile(KotlinScriptEnginePool.kt:50)
            at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:29)
            ... 3 more
```
and 
```
SuspendFunWithCoroutineScopeReceiverSpec > SuspendFunWithCoroutineScopeReceiver rule > no reports when suspend function has Long as receiver() FAILED
    io.github.detekt.test.utils.KotlinScriptException: Given Kotlin code is invalid.
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:37)
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:35)
        at app//io.github.detekt.test.utils.KotlinScriptEngine.compile(KotlinScriptEngine.kt:23)
        at app//io.gitlab.arturbosch.detekt.test.RuleExtensionsKt.compileAndLintWithContext(RuleExtensions.kt:59)
        at app//io.gitlab.arturbosch.detekt.rules.coroutines.SuspendFunWithCoroutineScopeReceiverSpec$SuspendFunWithCoroutineScopeReceiver rule.no reports when suspend function has Long as receiver(SuspendFunWithCoroutineScopeReceiverSpec.kt:127)

        Caused by:
        javax.script.ScriptException: Error: error: unresolved reference: coroutineScope
        suspend fun Long.foo() = coroutineScope {
                                 ^
        error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
        public fun CoroutineScope.launch(context: CoroutineContext = ..., start: CoroutineStart = ..., block: suspend CoroutineScope.() -> Unit): Job defined in kotlinx.coroutines
            launch {
            ^
            at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:74)
            at app//org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
            at app//io.github.detekt.test.utils.PooledScriptEngine.compile(KotlinScriptEnginePool.kt:50)
            at app//io.github.detekt.test.utils.KotlinScriptEngine.compileWithRetryOnFrontendException(KotlinScriptEngine.kt:29)
            ... 4 more
```

## Your Environment

* Version of detekt used: Latest main branch of detekt
* Version of Gradle used (if applicable):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by TWiStErRob** [comment]
Root cause analysis on why this happened (not complete): https://github.com/detekt/detekt/issues/5739
