### ISSUE TITLE
HtmlReport error in rule: Indentation

### ISSUE THREAD

**Issue by ben-j69** [detekt/detekt#5890]
I found an error in the html report:
- Rule: Indentation
- Detekt version: 1.22.0
- Stacktrace:
```
java.lang.StringIndexOutOfBoundsException: begin 0, end 35, length 34
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
	at java.base/java.lang.String.substring(String.java:1907)
	at io.github.detekt.report.html.HtmlUtilsKt.writeErrorLine(HtmlUtils.kt:50)
	at io.github.detekt.report.html.HtmlUtilsKt.access$writeErrorLine(HtmlUtils.kt:1)
	at io.github.detekt.report.html.HtmlUtilsKt.snippetCode(HtmlUtils.kt:34)
```
- How to reproduce it: 
While execute ./gradlew detekt

**Comment by cortinico** [comment]
> I found an error in the html report:

What do you mean "in the html report"?
Can you provide a bit more context?

**Comment by cortinico** [comment]
> It is the automated report on github. This error is displayed in the html report generated from my app analysis.

Could you share the report?

**Comment by BraisGabin** [comment]
This can be closed. It's a known issue and really hard to fix because ktlint changes the source code so when the reporter looks for the snippet it could not find it.

Thanks for the report.
