### ISSUE TITLE
[IDE Plugin] Stackoverflow Error

### ISSUE THREAD

**Issue by Nek-12** [detekt/detekt#6177]
## Steps to Reproduce
I am not sure how to reproduce this. I'm reporting an IDE error message

## Your Environment

* Version of detekt used: 1.23.0
* Version of Gradle used (if applicable): 8.1.1
* Gradle scan link (add `--scan` option when running the gradle task): no thanks
* Operating System and version: MacOS 13.3
* Link to your project (if it's a public repository): private

```
java.lang.StackOverflowError
	at java.base/java.util.Collections$SetFromMap.isEmpty(Collections.java:5682)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:145)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:227)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:350)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStubOrPsiChild(StubBasedPsiElementBase.java:360)
	at org.jetbrains.kotlin.psi.KtClassOrObject.getSuperTypeList(KtClassOrObject.kt:43)
	at org.jetbrains.kotlin.psi.KtClassOrObject.getSuperTypeListEntries(KtClassOrObject.kt:45)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass$delegateExpressions$2.invoke(AbstractKotlinUClass.kt:43)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass$delegateExpressions$2.invoke(AbstractKotlinUClass.kt:42)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.getDelegateExpressions(AbstractKotlinUClass.kt:42)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:97)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	at org.jetbrains.uast.UEnumConstant.accept(UVariable.kt:148)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	at org.jetbrains.uast.UEnumConstant.accept(UVariable.kt:148)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	at org.jetbrains.uast.UEnumConstant.accept(UVariable.kt:148)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	at org.jetbrains.uast.UEnumConstant.accept(UVariable.kt:148)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	at org.jetbrains.uast.UEnumConstant.accept(UVariable.kt:148)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:99)
	at io.ktor.ide.oas.KtorOasStatusCodeVisitor.visitExpression(KtorOasArgumentVisitors.kt:45)
	at org.jetbrains.uast.visitor.UastVisitor.visitSimpleNameReferenceExpression(UastVisitor.kt:27)
	at org.jetbrains.uast.USimpleNameReferenceExpression.accept(USimpleNameReferenceExpression.kt:19)
	/* ... repeats 50 times or so ... */
```

**Comment by Nek-12** [comment]
If I look at the stacktrace, there is literally nothing related to Detekt, but the error is marked as exception in the Detekt plugin. 

![image](https://github.com/detekt/detekt/assets/46318640/0387bf88-ea55-40b5-8e98-a3fc4a6d3eb9)
