### ISSUE TITLE
HtmlReport error in rule: NestedBlockDepth

### ISSUE THREAD

**Issue by cies** [detekt/detekt#6743]
I found an error in the html report:
- Rule: NestedBlockDepth
- detekt version: 1.23.4"}
- Stacktrace:
```
java.lang.StringIndexOutOfBoundsException: Range [0, 83) out of bounds for length 14
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
```
- How to reproduce it: not sure.

**Comment by 3flex** [comment]
I'm sorry but this isn't enough to investigate - we'll need a full stack trace if you can't provide a reproducer, but a reproducer will be much more helpful.
