### ISSUE TITLE
Pre-Commit Detekt CLI: Exception in thread "main" java.lang.IllegalArgumentException: Provided path ''

### ISSUE THREAD

**Issue by MirzaUkas** [detekt/detekt#6981]
## Expected Behavior
Run detekt using a Git pre-commit hook configuration (https://detekt.dev/docs/gettingstarted/git-pre-commit-hook) works using detekt CLI. 

this is my pre-commit file, the difference with official docs is `--config` parameter to get my detekt rules

```
#!/bin/bash

echo "Running detekt check..."

fileArray=($@)
detektInput=$(IFS=,;printf  "%s" "${fileArray[*]}")

echo "Input files: $detektInput"

# Get the root directory of the Git repository
rootDir=$(git rev-parse --show-toplevel)
echo "Root project directory: $rootDir"

OUTPUT=$(detekt --config "$rootDir/build-logic/convention/detekt/detekt.yml" --input "$detektInput" 2>&1)
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo $OUTPUT
  echo "***********************************************"
  echo "                 detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
```

## Observed Behavior
Instead of successfully checking the committed files and get the result, I got this error when commit from Android Studio VCS
```
00:02:04.299: [project-name] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- path/to/committed/file.kt
00:02:04.314: [project-name] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false commit -F /private/var/folders/8z/fb_rd6jj3qg7zv60btlqz7_w0000gn/T/git-commit-msg-.txt --
Running detekt check...
Input files: 
Root project directory: root/project/path
Exception in thread "main" java.lang.IllegalArgumentException: Provided path '' is empty. at io.gitlab.arturbosch.detekt.cli.ExistingPathConverter.convert(ArgumentConverters.kt:13) at io.gitlab.arturbosch.detekt.cli.ExistingPathConverter.convert(ArgumentConverters.kt:11) at io.gitlab.arturbosch.detekt.cli.DetektInputPathConverter$convert$2.invoke(ArgumentConverters.kt:31) at io.gitlab.arturbosch.detekt.cli.DetektInputPathConverter$convert$2.invoke(ArgumentConverters.kt:31) at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210) at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:811) at io.gitlab.arturbosch.detekt.cli.DetektInputPathConverter$DefaultImpls.convert(ArgumentConverters.kt:32) at io.gitlab.arturbosch.detekt.cli.MultipleExistingPathConverter.convert(ArgumentConverters.kt:41) at io.gitlab.arturbosch.detekt.cli.CliArgs$inputPaths$2.invoke(CliArgs.kt:193) at io.gitlab.arturbosch.detekt.cli.CliArgs$inputPaths$2.invoke(CliArgs.kt:192) at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) at io.gitlab.arturbosch.detekt.cli.CliArgs.getInputPaths(CliArgs.kt:192) at io.gitlab.arturbosch.detekt.cli.SpecKt$createSpec$1$2.invoke(Spec.kt:18) at io.gitlab.arturbosch.detekt.cli.SpecKt$createSpec$1$2.invoke(Spec.kt:16) at io.github.detekt.tooling.dsl.ProcessingSpecBuilder.project(ProcessingSpecBuilder.kt:37) at io.gitlab.arturbosch.detekt.cli.SpecKt$createSpec$1.invoke(Spec.kt:16) at io.gitlab.arturbosch.detekt.cli.SpecKt$createSpec$1.invoke(Spec.kt:9) at io.github.detekt.tooling.dsl.ProcessingSpecBuilderKt.processingSpec(ProcessingSpecBuilder.kt:15) at io.github.detekt.tooling.api.spec.ProcessingSpec$Companion.invoke(ProcessingSpec.kt:23) at io.gitlab.arturbosch.detekt.cli.SpecKt.createSpec(Spec.kt:9) at io.gitlab.arturbosch.detekt.cli.runners.Runner.<init>(Runner.kt:20) at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:31) at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:14) at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:20)
***********************************************
                 detekt failed                 
 Please fix the above issues before committing 
***********************************************
```

## Steps to Reproduce
1. brew install detekt
2. save pre-commit file into `<<your-repo>>/.git/hooks/pre-commit`
3. change permissions `chmod +x pre-commit`
4. commit single/multiple files using Android Studio VCS / git commit command manually 

## Context
I've tried to make detekt command run faster by narrowing the files based on committed files using `--input` parameter

## Your Environment
* Version of detekt cli used: 1.23.5
* Version of detekt gradle plugin: 1.23.0
* Version of Gradle used: 8.1.1
* Operating System and version: Mac OS Sonoma 14.2.1

**Comment by YMonnier** [comment]
I have the same issue.

I just followed the instruction here: https://detekt.dev/docs/gettingstarted/git-pre-commit-hook
The input files is empty

```
❯ git commit
Running detekt check...
Input files:
Exception in thread "main" java.lang.IllegalArgumentException: Provided path '' is empty. at io.gitlab.arturbosch.detekt.cli.ExistingPathConverter.convert(ArgumentConverters.kt:13) at io.gitlab.arturbosch.detekt.cli.ExistingPathConverter.convert(ArgumentConverters.kt:11) at io.gitlab.arturbosch.detekt.cli.DetektInputPathConverter$convert$2.invoke(ArgumentConverters.kt:31) at io.gitlab.arturbosch.detekt.cli.DetektInputPathConverter$convert$2.invoke(ArgumentConverters.kt:31) at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210) at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:811) at io.gitlab.arturbosch.detekt.cli.DetektInputPathConverter$DefaultImpls.convert(ArgumentConverters.kt:32) at io.gitlab.arturbosch.detekt.cli.MultipleExistingPathConverter.convert(ArgumentConverters.kt:41) at io.gitlab.arturbosch.detekt.cli.CliArgs$inputPaths$2.invoke(CliArgs.kt:193) at io.gitlab.arturbosch.detekt.cli.CliArgs$inputPaths$2.invoke(CliArgs.kt:192) at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) at io.gitlab.arturbosch.detekt.cli.CliArgs.getInputPaths(CliArgs.kt:192) at io.gitlab.arturbosch.detekt.cli.SpecKt$createSpec$1$2.invoke(Spec.kt:18) at io.gitlab.arturbosch.detekt.cli.SpecKt$createSpec$1$2.invoke(Spec.kt:16) at io.github.detekt.tooling.dsl.ProcessingSpecBuilder.project(ProcessingSpecBuilder.kt:37) at io.gitlab.arturbosch.detekt.cli.SpecKt$createSpec$1.invoke(Spec.kt:16) at io.gitlab.arturbosch.detekt.cli.SpecKt$createSpec$1.invoke(Spec.kt:9) at io.github.detekt.tooling.dsl.ProcessingSpecBuilderKt.processingSpec(ProcessingSpecBuilder.kt:15) at io.github.detekt.tooling.api.spec.ProcessingSpec$Companion.invoke(ProcessingSpec.kt:23) at io.gitlab.arturbosch.detekt.cli.SpecKt.createSpec(Spec.kt:9) at io.gitlab.arturbosch.detekt.cli.runners.Runner.<init>(Runner.kt:20) at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:31) at io.gitlab.arturbosch.detekt.cli.CliRunner.run(CliRunner.kt:14) at io.gitlab.arturbosch.detekt.cli.Main.main(Main.kt:20)
***********************************************
                 detekt failed
 Please fix the above issues before committing
***********************************************
```

**Comment by YMonnier** [comment]
@MirzaUkas 

I fixed it by updating the `fileArray` value. 
Now, I am getting staged files with a git command instead of a bash argument.

```bash
#!/bin/bash

echo "Running detekt check..."

fileArray=$(git diff --cached --name-only --diff-filter=ACM -z | xargs -0)
detektInput=$(IFS=,;printf  "%s" "${fileArray[*]}")

echo "Input files: $detektInput"

# Get the root directory of the Git repository
rootDir=$(git rev-parse --show-toplevel)
echo "Root project directory: $rootDir"

OUTPUT=$(detekt --config "$rootDir/build-logic/convention/detekt/detekt.yml" --input "$detektInput" 2>&1)
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo $OUTPUT
  echo "***********************************************"
  echo "                 detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
```

**Comment by BraisGabin** [comment]
If this version is better, please create a PR so we improve the documentation
