### ISSUE TITLE
Detekt is not compatible with Android Studio Ladybug (JRE 21)

### ISSUE THREAD

**Issue by hkosacki** [detekt/detekt#7556]
## Expected Behavior
Detekt plugin should run on `Android Studio Ladybug | 2024.2.1 Canary 4`

## Observed Behavior
The gradle project fails to sync on `Android Studio Ladybug | 2024.2.1 Canary 4` with the following message:
```
Execution failed for task ':my-project:detekt'.
> Invalid value (21) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```

Stacktrace:

```
Caused by: org.gradle.api.GradleException: Invalid value (21) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
	at io.gitlab.arturbosch.detekt.invoke.DefaultCliInvoker.invokeCli(DetektInvoker.kt:102)
	at io.gitlab.arturbosch.detekt.Detekt.check(Detekt.kt:269)
	(...)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at io.gitlab.arturbosch.detekt.invoke.DefaultCliInvoker.invokeCli(DetektInvoker.kt:96)
	... 127 more
Caused by: java.lang.IllegalStateException: Invalid value (21) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
	at io.gitlab.arturbosch.detekt.core.settings.EnvironmentAwareKt.parseJvmTarget(EnvironmentAware.kt:67)
	at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade$environment$2.invoke(EnvironmentAware.kt:40)
	at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade$environment$2.invoke(EnvironmentAware.kt:35)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.gitlab.arturbosch.detekt.core.settings.EnvironmentFacade.getEnvironment(EnvironmentAware.kt:35)
	at io.gitlab.arturbosch.detekt.core.ProcessingSettings.getEnvironment(ProcessingSettings.kt)
	at io.gitlab.arturbosch.detekt.core.KtTreeCompiler.<init>(KtTreeCompiler.kt:18)
	at io.gitlab.arturbosch.detekt.core.tooling.ParsingStrategyKt$inputPathsToKtFiles$1.invoke(ParsingStrategy.kt:24)
	at io.gitlab.arturbosch.detekt.core.tooling.ParsingStrategyKt$inputPathsToKtFiles$1.invoke(ParsingStrategy.kt:23)
	at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$filesToAnalyze$1.invoke(Lifecycle.kt:38)
	at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$analyze$filesToAnalyze$1.invoke(Lifecycle.kt:38)
	at io.gitlab.arturbosch.detekt.core.util.PerformanceMonitor.measure(PerformanceMonitor.kt:43)
	at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.measure(Lifecycle.kt:34)
	at io.gitlab.arturbosch.detekt.core.tooling.Lifecycle$DefaultImpls.analyze(Lifecycle.kt:38)
	at io.gitlab.arturbosch.detekt.core.tooling.DefaultLifecycle.analyze(Lifecycle.kt:61)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:48)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade$runAnalysis$1.invoke(AnalysisFacade.kt:47)
	at io.gitlab.arturbosch.detekt.core.tooling.ProcessingSpecSettingsBridgeKt.withSettings(ProcessingSpecSettingsBridge.kt:26)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.runAnalysis$detekt_core(AnalysisFacade.kt:47)
	at io.gitlab.arturbosch.detekt.core.tooling.AnalysisFacade.run(AnalysisFacade.kt:25)
	at io.gitlab.arturbosch.detekt.cli.runners.Runner.call(Runner.kt:33)
	at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:23)
	... 129 more
```

## Steps to Reproduce
Please try to open any Android project that has Detekt integrated with the newest version of Android Studio Canary Ladybug.

## Context
The issue is not happening on Android Studio Koala (current stable).

## Your Environment

```
Android Studio Ladybug | 2024.2.1 Canary 4
Build #AI-242.20224.159.2421.12169541, built on August 1, 2024
Runtime version: 21.0.3+-77717980-b509.4 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.5
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  dev.j-a.swift (1.1.0.354-242)
  Key Promoter X (2024.2.0)
  de.netnexus.camelcaseplugin (3.0.12)
  gherkin (242.20224.159)
  cucumber-java (242.20224.159)
  izhangzhihao.rainbow.brackets.lite (1.1.0)
  uk.co.ben-gibson.remote.repository.mapper (4.4.0)
```

**Comment by 3flex** [comment]
Just confirming you're using the IntelliJ plugin?

**Comment by hkosacki** [comment]
No, it's just pure gradle integration. All the plugins I have in my AS setup are listed in the `Your Environment` section.

**Comment by BraisGabin** [comment]
Which detekt version are you using? I have the last stable version running with Ladybug Canary 7.

**Comment by hkosacki** [comment]
I was running detekt `1.23.0`. Let me add this to the issue's description.

I just checked against `1.23.6`, and is seems it is fine. I must have missed the updates since then, since it was just working. It just popped up with newer AS release.

I'm sorry for the noise. Closing the issue.
